"""
Telemetry JSON Parser and Schema Validator for CLI Output Verification.

Validates structured JSON telemetry generated by `subq_cli --telemetry-json <path>`,
checking required metrics (mean, p50, p95, p99 latency, RTF, throughput),
statistical monotonicities, and performance thresholds.
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union


class TelemetryValidationError(AssertionError):
    """Raised when telemetry JSON fails schema validation or threshold checks."""
    pass


class TelemetryParser:
    """Parses and validates telemetry JSON output from subq_cli."""

    REQUIRED_METRICS = [
        ("mean_latency_us", "mean_latency_ms", "mean_latency"),
        ("p50_latency_us", "p50_latency_ms", "p50_latency", "median_latency_us"),
        ("p95_latency_us", "p95_latency_ms", "p95_latency"),
        ("p99_latency_us", "p99_latency_ms", "p99_latency"),
        ("throughput_samples_per_sec", "throughput_samples_sec", "throughput", "samples_per_sec"),
        ("real_time_factor", "rtf", "realtime_factor"),
    ]

    @staticmethod
    def load_telemetry(filepath: Union[str, Path]) -> Dict[str, Any]:
        """Loads and parses a telemetry JSON file from disk.
        
        Args:
            filepath: Path to the JSON telemetry file.
            
        Returns:
            Parsed dictionary containing telemetry data.
            
        Raises:
            FileNotFoundError: If telemetry file does not exist.
            ValueError: If file content is not valid JSON.
        """
        filepath = Path(filepath)
        if not filepath.is_file():
            raise FileNotFoundError(f"Telemetry JSON file not found at: {filepath}")

        with open(filepath, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError as e:
                raise ValueError(f"Failed to parse telemetry JSON from {filepath}: {e}")

        if not isinstance(data, dict):
            raise ValueError(f"Telemetry JSON root must be an object/dict, got {type(data).__name__}")

        return data

    @classmethod
    def validate_schema(cls, data: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """Validates that a telemetry dictionary contains all required fields and conforms to constraints.
        
        Args:
            data: Telemetry data dictionary.
            
        Returns:
            Tuple of (is_valid: bool, errors: List[str]).
        """
        errors: List[str] = []

        # Check required fields with alternative naming aliases
        found_fields = {}
        for aliases in cls.REQUIRED_METRICS:
            matched_key = None
            for key in aliases:
                if key in data:
                    matched_key = key
                    break
            if matched_key is None:
                errors.append(f"Missing required metric: one of {aliases} must be present.")
            else:
                val = data[matched_key]
                if not isinstance(val, (int, float)):
                    errors.append(f"Metric '{matched_key}' must be numeric (int/float), got {type(val).__name__}: {val}")
                elif val < 0:
                    errors.append(f"Metric '{matched_key}' cannot be negative, got {val}")
                else:
                    found_fields[aliases[0]] = float(val)

        # Check monotonic percentiles: p50 <= p95 <= p99
        p50 = found_fields.get("p50_latency_us")
        p95 = found_fields.get("p95_latency_us")
        p99 = found_fields.get("p99_latency_us")

        if p50 is not None and p95 is not None and p50 > p95 + 1e-3:
            errors.append(f"Monotonicity violation: p50 ({p50}) > p95 ({p95})")
        if p95 is not None and p99 is not None and p95 > p99 + 1e-3:
            errors.append(f"Monotonicity violation: p95 ({p95}) > p99 ({p99})")

        # Check processed samples count if present
        for sample_count_key in ["total_samples_processed", "samples_processed", "total_samples"]:
            if sample_count_key in data:
                val = data[sample_count_key]
                if not isinstance(val, int) or val < 0:
                    errors.append(f"Field '{sample_count_key}' must be a non-negative integer, got {val}")

        return len(errors) == 0, errors

    @classmethod
    def assert_valid(
        cls,
        filepath_or_data: Union[str, Path, Dict[str, Any]],
        max_p99_latency_us: Optional[float] = None,
        min_throughput: Optional[float] = None,
        max_rtf: Optional[float] = 1.0
    ) -> Dict[str, Any]:
        """Asserts that telemetry data is schema-valid and meets performance thresholds.
        
        Args:
            filepath_or_data: Filepath to JSON or already loaded dict.
            max_p99_latency_us: Optional upper bound on p99 latency in microseconds.
            min_throughput: Optional lower bound on throughput (samples/sec).
            max_rtf: Optional upper bound on Real-Time Factor (default 1.0 for real-time).
            
        Returns:
            Validated telemetry dictionary.
            
        Raises:
            TelemetryValidationError: If validation or threshold check fails.
        """
        if isinstance(filepath_or_data, (str, Path)):
            data = cls.load_telemetry(filepath_or_data)
        else:
            data = filepath_or_data

        is_valid, errors = cls.validate_schema(data)
        if not is_valid:
            raise TelemetryValidationError(
                f"Telemetry schema validation failed with {len(errors)} error(s):\n" +
                "\n".join(f"  - {err}" for err in errors)
            )

        # Performance threshold checks
        rtf_key = next((k for k in ["real_time_factor", "rtf", "realtime_factor"] if k in data), None)
        if rtf_key and max_rtf is not None:
            actual_rtf = float(data[rtf_key])
            if actual_rtf > max_rtf:
                raise TelemetryValidationError(
                    f"Real-Time Factor {actual_rtf:.4f} exceeded maximum threshold {max_rtf:.4f}"
                )

        p99_key = next((k for k in ["p99_latency_us", "p99_latency"] if k in data), None)
        if p99_key and max_p99_latency_us is not None:
            actual_p99 = float(data[p99_key])
            if actual_p99 > max_p99_latency_us:
                raise TelemetryValidationError(
                    f"p99 latency {actual_p99:.2f} us exceeded maximum threshold {max_p99_latency_us:.2f} us"
                )

        thr_key = next((k for k in ["throughput_samples_per_sec", "throughput_samples_sec", "throughput"] if k in data), None)
        if thr_key and min_throughput is not None:
            actual_thr = float(data[thr_key])
            if actual_thr < min_throughput:
                raise TelemetryValidationError(
                    f"Throughput {actual_thr:.2f} samples/sec is below minimum threshold {min_throughput:.2f}"
                )

        return data
